### ISSUE TITLE
Latex-chunk fail to run (I think) when knitting to HTML

### ISSUE THREAD

**Issue by veggabo** [SimonSchowanek/MINA_DSF#2]
Hi @SimonSchowanek or anyone else who may have some insight to this,

I'm trying out knitting the "Rmarkdown_Manuscript.Rmd" to HTML and Word, and while I don't get any errors, I see that the code chunk in Latex right after the "Results" section fails to run. At least, I can't manage to get it into the final files, and the reference to the figure just states

> Figure ???

I have installed TinyTex, and run the command `tinytex::install_tinytex()`. When I run the command, I get the following warning: 
> Found 'C:\Users\vebo\AppData\Roaming\TinyTeX\bin\win32\tlmgr.bat', which indicates a LaTeX distribution may have existed in the system.

I have let the command run once, ignoring the warning. 

So, do you have any idea what may be the issue here? Note that knitting to PDF works fine. 

PS: I tried to attach my files, but I wasn't allowed :(

**Comment by SimonSchowanek** [comment]
ok, so the tinytex warning is actually good: it says that latex already exists. So that is not the problem. Instead, I suspect that filepaths are at the root of the issue. 

I seem to understand that the issue is this section?

`\begin{figure}[h]
  \centering
  {\includegraphics[width=15cm]{Figure1.png}}
  \caption{Here is a plot}
  \label{fig:scatterplot}
\end{figure}`

I suspect Rmarkdown does not find the file called scatterplot, and that's why the question marks appear. Make sure that you open the correct R project (the one in the repo) as the filepaths used here are relative.

**Comment by SimonSchowanek** [comment]
So it appears that the latex code we mentioned above works well when knitting to pdf, but not when knitting to HTML or word. I think the most obvious solution would be the add the image in another way (ideally also one that allows for in-text referencing), but right now I don't know what alternative I would suggest.
